import type { Metadata } from "next";
import "./globals.css";

const workSans = {
  variable: "--font-work-sans",
  name: "Work Sans",
  subsets: ["latin"],

export const metadata: Metadata = {
  title: "Pitch Startup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
